import {ColumnActions} from "../common/column-actions";

export interface LoanAll {
    id: number;
    sharedLoanId: number;
    archiveNumber: number;
    customerId: number;
    customerNumber: number;
    loanSerial: number;
    loanTitle: string;
    loanStatusTypeId: string;
    loanStatusTypeDesc: string;
    loanNumber: string;
    waitDuration: number;
    eachInstallmentAmount: number;
    firstInstallmentDateFa: string;
    lastInstallmentDateFa: string;
    notPaiedAmount: number;
    customerPaiedAmount: number;
    visionAmount: number;
    remainAmount: number;
    remainFromMain: number;
    remainFromProfit: number;
    delayedAmount: number;
    numberOfDelayedInstallment: number;
    firstDelayedInstallmentDateFa: string;
    lastDelayedInstallmentDateFa: string;
    totalRemainAmount: number;
    totalRemainAmountWithPenalty: number;
    registerDateFa: string;
//     loanContract: LoanContractDto;
//     customerPlans: [CustomerPlanDto];
//     loanPayCards: [LoanPayCard];
//     loanPayBanks: [LoanPayBanksDto];
//     loanPayInfos: [LoanPayInfoDto];
//     loanPayDetails: [LoanPayDetailDto];
//     loanCollats: [LoanCollatDto];
//     loanGuarantees: [LoanGuaranteeDto];
//     customer: CustomerDto;
//     factLoanAcc: any;
//     actors: [ActorDto];
//     loanActions: [LoanActionDto];
//     introducers: [CustomerDto];
//     guarantors: [CustomerDto];
//     attachments: [AttachmentDto];
//     relatedLoanItems: [RelatedLoanItem];
//     loanActionLogs: [LoanActionLogs];
//     branch: BranchDto;
//     currentActor: ActorDto;
//     lastAction: LoanActionDto;
//     loanStatusType: LoanStatusTypeDto;
//     activeActor: ActorDto;
//     lastPayBank: LoanPayBankDto;
//     loanMinorType: LoanMinorTypeDto;
    lastActorName: string;
    lastActionName: string;
    roleName: string;
    isUserActor: boolean;
    installmentCount: number;
    lastActorId: number;
    remainWaitProfitTotalAmount: number;
    loanInstallmentTypeDesc: string;
    lastActionTitle: string;
    lastActorUserName: string;
    lastActorUserId: number;
    referenceTotalDelayedAmount: number;
    referenceNumberOfDelayedInstallment: number;
    lastPaymentInfoDateFa: string;
    lastPaymentInfoAmount: number;
    lastActorsDateFa: string;
    lastActionDateFa: string;
    // loanCustomer: CustomerDto;
    legalReferenceTypeId: number;
    legalUserId: number;
    isLegal: boolean;
    loanId: number;
    isDeathName: string;
    legalName: string;
    isLegalReady: boolean;
    columnActions: ColumnActions[];
}