import {CustomerAddress} from "./customer-address";
import {Guaranty} from "./guaranty";
import {Collate} from "./collate";
import {AccModel} from "./acc-model";

export interface LoanDetail {
    loanId: number;
    id: number;
    loanNumber: string;
    customerNumber: number;
    loanSerial: number;
    customerId: number;
    branchCode: number;
    branchName: string;
    supervisorCode: number;
    supervisorName: string;
    lastActorId: number;
    lastActorUserId: number;
    lastActorUserName: string;
    lastActorsDateFa: string;
    lastActionId: number;
    lastActionTypeId: number;
    lastActionTypeDesc: string;
    fullCustomerName: string;
    lastPaymentInfoDateFa: string;
    lastPaymentInfoAmount: number;
    waitDuration: number;
    firstName: string;
    lastName: string;
    fatherName: string;
    nationalNumber: string;
    nationalityTypeId: number;
    nationalityTypeDesc: string;
    idNumber: string;
    isMarried: boolean;
    isMarriedDesc: string;
    isFamilySupervisor: boolean;
    isFamilySupervisorDesc: string;
    isDeath: boolean;
    isDeathName: string;
    legalNationalityNumber: string;
    legalEconomicCode: string;
    legalRegistrationNumber: string;
    legalRegistrationLocation: string;
    beginDateFa: string;
    acceptAmount: number;
    loanPlanPhone: string;
    loanPlanMobile: string;
    loanPlanAddress: string;
    loanInstallmentTypeId: number;
    loanInstallmentTypeDesc: string;
    planNoId: number;
    planNoDesc: string;
    planTypeDesc: string;
    loanTitle: string;
    loanMinorTypeId: number;
    loanMinorTypeDesc: string;
    loanEconomicTypeDesc: string;
    loanCustomer: any;
    gender: boolean;
    loanCustomerAddressModel: [CustomerAddress];
    loanGuarantor: Guaranty[];
    loanIntroducers: Guaranty[];
    loanCollats: Collate[];
    lastActionTitle: string;
    lastActionDateFa: string;
    isUserActor: boolean;
    actorsCount: number;
    loanSystemTypeDesc: number;
    loanAccModelTotal: AccModel;
    longitude: string;
    latitude: string;
    isVerifyChange: boolean;
    veryfiyUserFullName: string;
    changeLonaPlanStateUser: string;
    hasLoanPlan: boolean;
    legalReferenceTypeId: number;
    legalUserId: number;
    endDateFa: string;
}

