export enum ActivitiesEnum {
  dashboard = 1,
  SecurityMenuRoot = 2,
  BasicInfoMenuRoot = 3,
  userManagement = 4,
  branchesManagement = 5,
  changePassword = 6,
  roleManagement = 7,
  forms = 8,
  GetBranchesAsync = 9,
  PaymentConfirmation = 127,
  GetLoanById = 133,
  CanCalculateEffectiveDate = 134,
  GetLoansQuery = 62,
  getLoanByIdQuery = 109,
  FilterCustomer = 110,
  FilterSupervisor = 111,
  GetAllBranches = 112,
  getLoanStatusType = 113,
  getLoanCollatTypesQuery = 114,
  GetReagent = 115,
  filterLoanMinorType = 116,
  getLoanInstallmentType = 117,
  getUser = 118,
  getAll = 119,
  GetAllActionTypes = 120,
  GetActionTypes = 121,
  GetLoanActionListQuery = 122,
  setLoanAction = 123,
  removeLoanAction = 124,
  getLoansActorsQuery = 125,
  deleteActor = 126,
  ComputeWageAmount = 127,
  RollBackActor = 128,
  SetActor = 129,
  refreshLoanDaily = 130,
  ComputeRespiteActor = 131,
  AddRelatedLoan = 132,
  uploadLoanImage = 133,
  RemoveUploadedFiles = 134,
  uploadCustomerImage = 135,
  uploadSurveyImage = 136,
  UploadFiles = 137,
  uploadUserImage = 138,
  hasDeathCustomer = 139,
  refreshLoan = 140,
  setLegal = 141,
  setDeath = 142,
  getUserListQuery = 143,
  setUser = 144,
  SetUserBranch = 145,
  deleteUserBranche = 146,
  SetUserRole = 147,
  deleteUserRole = 148,
  AddActorToLoans = 149,
  RemoveLoansActor = 150,
  FacilitiesInformation = 151,
  SetChangeLoanPlanStateRequest,
  VerifyChangeLoanPlanStateRequest,
  updateFacilitiesLoans,
  PrintMontlyRequest,
  CityManagerConfirmation = 159,
  CityManagerCancelConfirmation = 160,
  ProvinceManagerConfirmation = 161,
  ProvinceManagerCancelConfirmation = 162,
  GetSurveyDocument = 163,
  ReturnToUser = 164,
  SetOtherPlanNo = 170,
  ConfirmUsersMontlyPayment = 171,
  SetActionDate = 172,
  SetCartable = 173,
  RemoveSurveyImage = 174,
  RemoveCartable = 175,
  ConfirmChangeLocation,
  SetLoanPlanNo = 177,
  RemoveAttachment = 178,
  ShowConfirmedActor = 181,
  ActorAggregatedWage = 182,
  SupervisorAggregatedWage,
  BranchAggregatedWage = 184,
  ReferenceToLegal = 186,
  ConfirmLegalReference = 187,
  NotConfirmLegalReference = 188
}



