export enum LoanActionEnum {
    ekhtareKatbi = 3,
    tamaseTelephoni = 4,
    ekhtareHosneNiat = 6,
    ekhtareKasrAzHoghoogh = 7,
    ersaleEkhtarAzTarighePost = 8,
    beMotaghaziMohlatDadeShod = 9,
    bargashteCheck = 11,
    ersalEzharName = 12,
    sodooreEjraeye = 13,
    ekhtarBeManzeleZamen = 14,
    ekhtarBeManzelVamGirande = 15,
    ersalePayamak = 16,
    daryafteCheckejahateTasvie = 17,
    ersaleEkhatarBeSahebeCheck = 18,
    tamaseTelephoniBaZamen = 19,
    taahodNamePardakhtMoavaghat = 20,
    bedoneEghdam = 21,
    tamasbaniroo = 22,
    tamasBaKarshenaseVosoolSetad = 23
}